mariadb_project/maria/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.search, name='search'),
]

mariadb_project/mariadb_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maria.urls')),
]

mariadb_project/maria/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ProfileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    StudentID = models.CharField(max_length=20)
    NickName = models.TextField(max_length=30)

class UserPhone(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    UserPhone = models.CharField(max_length=30)

mariadb_project/maria/views.py
import math
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from .models import ProfileUser, UserPhone
from django.core.paginator import Paginator
# Create your views here.
def search(request):
    alluserdata = User.objects.all().order_by('profileuser__StudentID')
    # order_by에서 다른 모델 객체를 이용할땐 이중 언더바 사용

    paginator = Paginator(alluserdata, 5)    
    # 사용자 정보 5개를 한 페이지로 자름.
    page = request.GET.get('page')
    # request된 페이지 번호를 알아내 변수에 담는다.

    user_page = paginator.get_page(page)
    # 내가 원하는 페이지 가져오기

    show_page_range = 5
    
    max_index = len(paginator.page_range)

    current_page = int(page) if page else 1
    start_index = int((current_page - 1) / show_page_range ) * show_page_range
    end_index = start_index + show_page_range
    if end_index >= max_index:
        end_index = max_index
    
    page_range = paginator.page_range[start_index:end_index]
    context = {'alluserdata':alluserdata, 'user_page':user_page, 'page_range':page_range}
    
    return render(request, 'search.html', context)
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('login')
        else:
            return render(request, 'login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'login.html')
    return render(request, 'login.html')

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(username=request.POST['user_name'], password=request.POST['password1'])
            nick_name = request.POST['nick_name']
            sid = request.POST['student_id']
            user_phone = request.POST['user_phone']
            user_profile = ProfileUser(user=user, NickName=nick_name, StudentID=sid)
            user_phone = UserPhone(user=user, UserPhone=user_phone)
            user_profile.save()
            user_phone.save()
            return redirect('login')
    return render(request, 'signup.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('login')
    return render(request, 'login.html')

mariadb_project/maria/templates/login.html
<h1> 로그인 예제 </h1>
{% if user.is_authenticated %}
<p>{{user.profileuser.NickName}} 로그인중</p>
<p>{{user.username}} 로그인중</p>
<a href="javascript:{document.getElementById('logout').submit()}">Logout</a>
<form id="logout" method="POST" action="{% url 'logout' %}">
	{% csrf_token %} <input type="hidden" />
</form>
{% else %}
<form action="" method="POST">
    {% csrf_token%}
    UserID:
    <br>
    <input name="username" type="text" placeholder="아이디 입력">
    <br>
    PassWord:
    <br>
    <input name="password" type="password" value="">
    <br>
    Confirm PassWord:
    <br>
    <input type="submit" value="Login">
</form>
{% endif %}
<a href="{%url 'signup'%}">회원가입하기</a>
<a href="{%url 'search'%}">학생정보보기</a>

mariadb_project/maria/templates/search.html
<!DOCTYPE html>
<html lang="ko">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<head>
    <meta charset="utf-8">
    <title>학생 정보 출력</title>
</head>

<body>
    <br>
    <div class="container">
        <table class="talbe table-striped" width="100%">
            <thead>
                <tr>
                    <th>User ID</th>
                    <th>닉네임</th>
                    <th>학번</th>
                    <th>전화번호</th>
                </tr>
            </thead>
            {% for user_page in user_page %}
            <tr>
                <td>{{user_page.username}}</td>
                <td>{{user_page.profileuser.NickName}}</td>
                <td>{{user_page.profileuser.StudentID}}</td>
                {% for user_phone in user_page.userphone_set.all %}
                <td>{{user_phone.UserPhone}}</td>
                {%endfor%}
            </tr>
            {%endfor%}
        </table>
        <div class="container">
            <br>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <a class="page-link" href="?page=1">처음</a>
                    {%if user_page.has_previous%}
                    <a class="page-link" href="?page={{user_page.previous_page_number}}">이전</a>
                    {% else %}
                    <a class="page-link" href="#">이전</a>
                    {%endif%}
                    {% for page in page_range%}
                    {%if page == user_page.number%}
                    <li class="page-item active" aria-current="page" {% if page == user_page.number %}class="active"
                        {% endif %}>
                        <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
                    </li>
                    {%else%}
                    <li class="page-item" {% if page == user_page.number %}class="active" {% endif %}>
                        <a class="page-link" href="?page={{page}}">{{page}}</a>
                    </li>
                    {%endif%}

                    {% endfor %}
                    {%if user_page.has_next%}
                    <a class="page-link" href="?page={{user_page.next_page_number}}">다음</a>
                    {%else%}
                    <a class="page-link" href="#">다음</a>
                    {%endif%}
                    <a class="page-link" href="?page={{user_page.paginator.num_pages}}">끝</a>
                </ul>
            </nav>

        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

mariadb_project/maria/templates/signup.html
<h1> 회원가입 예제 Maria DB사용</h1>

<form action="{%url 'signup'%}" method="POST">
    {% csrf_token %}
    UserID:
    <br>
    <input name="user_name" type="text" value="">
    <br>
    PassWord:
    <br>
    <input name="password1" type="password" value="">
    <br>
    Confirm PassWord:
    <br>
    <input name="password2" type="password" value="">
    <br>
    NickName:
    <br>
    <input name="nick_name" type="text" value="">
    <br>
    StudentID:
    <br>
    <input name="student_id" type="text" value="">
    <br>
    PhoneNumber:
    <br>
    <input name="user_phone" type="text" value="">
    <br>
    <br>
    <input type="submit">
</form>